name: Build & Test

on:
  # disable integration test run for breaking changes adoption
  push:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Do format
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.24.0
          ./build.sh format
          git status
      - name: Check format
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Error: Please format files via ./build.sh format first ";
            echo "Found not format files:"
            git status --porcelain
            exit 1;
          fi

  build-ubuntu:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v ./...

  build-windows:
    needs: [ lint ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v ./...

# disable integration test run for breaking changes adoption
#  integration-test:
#    needs: [ build-ubuntu, build-windows ]
#    uses: go-echarts/go-echarts-pipeline/.github/workflows/integration.yml@main
