name: Build & Test


on:
  push:
    branches: [ "master", "format-action" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Do format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          ./build.sh format 
          git status
      - name: Check format
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Error: Please format files via ./build.sh format first ";
            exit 1;
          fi

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
  build-ubuntu:
    runs-on: ubuntu-latest
    needs: [ lint, dependency-review ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v ./...

  build-windows:
    needs: [ lint, dependency-review ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v ./...
