name: Integration test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Checkout another repository
        uses: actions/checkout@v4
        with:
          repository: 'go-echarts/examples'
          path: 'examples'
      - name: Check repos
        run: |
          ls -l
          ls examples/
      - name: Replace dependency and server
        run: |
          echo "replace github.com/go-echarts/go-echarts/v2 => ../../go-echarts" >> examples/go.mod
          sed '/ListenAndServe/d' -i examples/main.go
      - name: Check Examples changed files
        run: |
          cat examples/go.mod
          cat examples/main.go
      - name: Run Examples generate html files
        run: |
          go run examples/main.go
      - name: Check Examples generate html files
        run: |
          ls examples/examples/
      
          
