name: Integration test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  checkout-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Checkout another repository
        uses: actions/checkout@v4
        with:
          repository: 'go-echarts/examples'
          #         remove
          ref: 'v2.4-rc'
          path: 'examples'
      - name: Check repos
        run: |
          echo "Main repo ==>"
          ls -l
          echo "Example repo ==>"
          ls examples/
      - name: Run Examples generate original html files on tag
        run: |
          cd examples
          echo "Currently working on go-echarts version ===>"
          cat go.mod
          go mod tidy
          go run . false
      - name: Check Examples generate html files and mv as snapshot
        run: |
          cd examples
          ls examples/html/
          mkdir -p examples/snapshot
          mv examples/html/*.html examples/snapshot/
          ls examples/snapshot/

      - name: Replace dependency and server
        run: |
          cd examples
          echo "replace github.com/go-echarts/go-echarts/v2 => ../../go-echarts" >> go.mod
      - name: Check Examples changed files
        run: |
          cd examples
          cat go.mod
      - name: Run Examples generate html files
        run: |
          cd examples
          go mod tidy
          go run . false
      - name: Check Examples generate html files
        run: |
          ls examples/examples/html/
      
          
