name: Integration test

on:
  push:
    branches: [ "integration-action" ]
  workflow_dispatch:

jobs:
  integration-test:
    uses: go-echarts/go-echarts-pipeline/workflows/.github/integration.yml@main
